### ISSUE TITLE
"missing" error when trying to signup

### ISSUE THREAD

**Issue by castos** [bigcompany/safewallet#6]
I have already installed _couchdb_ and configured it with creating database admin user.
Then have changed config file with admin's username and password.
Also I have created _resource_ database with

```
curl -X PUT localhost:5984/resource
```

But when running _safewallet's frontend_ and trying to signup something going wrong.
After completing the form and pressing _sign up now_ button the /signup page in browser shows

```
missing
```

Please help me to find where is the problem?

**Comment by Marak** [comment]
Have you tried running any of the tests?

**Comment by castos** [comment]
As you advised I have started _signups-test.js_
Here is  the whole report:

```
~/safewallet# node test/signups-test.js
connect: multipart: use parser (multiparty, busboy, formidable) directly
connect: limit: Restrict request size at location of read
TAP version 13
# start safewallet server
ok 1 no error
ok 2 server is returned
# signup with a new user
not ok 3 should be equal
  ---
    file:   /root/safewallet/node_modules/supertest/lib/test.js
    line:   205
    column: 12
    stack:
      - getCaller (/root/safewallet/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/root/safewallet/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/root/safewallet/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/root/safewallet/node_modules/tap/lib/tap-test.js:87:16)
      - /root/safewallet/test/signups-test.js:31:9
      - Test.assert (/root/safewallet/node_modules/supertest/lib/test.js:205:12)
      - Server.assert (/root/safewallet/node_modules/supertest/lib/test.js:132:12)
      - Server.g (events.js:180:16)
      - Server.EventEmitter.emit (events.js:92:17)
      - net.js:1276:10
    found:  ~
    wanted:
      name:    Error
      message: expected 301 "Moved Permanently", got 200 "OK"
      type:    ~
    type:
      found:  undefined
      wanted: undefined
  ...
not ok 4 should be equal
  ---
    file:   /root/safewallet/node_modules/supertest/lib/test.js
    line:   205
    column: 12
    stack:
      - getCaller (/root/safewallet/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/root/safewallet/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/root/safewallet/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/root/safewallet/node_modules/tap/lib/tap-test.js:87:16)
      - /root/safewallet/test/signups-test.js:32:9
      - Test.assert (/root/safewallet/node_modules/supertest/lib/test.js:205:12)
      - Server.assert (/root/safewallet/node_modules/supertest/lib/test.js:132:12)
      - Server.g (events.js:180:16)
      - Server.EventEmitter.emit (events.js:92:17)
      - net.js:1276:10
    found:  missing
    wanted: Moved Permanently. Redirecting to /wallet
    diff:   |
      FOUND:  missing
      WANTED: Moved Permanently. Redirecting to /walle
              ^ (at position = 0)
  ...
# try to get /account page while logged in ( with session from signup )
not ok 5 should be equal
  ---
    file:   /root/safewallet/node_modules/supertest/lib/test.js
    line:   205
    column: 12
    stack:
      - getCaller (/root/safewallet/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/root/safewallet/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/root/safewallet/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/root/safewallet/node_modules/tap/lib/tap-test.js:87:16)
      - /root/safewallet/test/signups-test.js:43:9
      - Test.assert (/root/safewallet/node_modules/supertest/lib/test.js:205:12)
      - Server.assert (/root/safewallet/node_modules/supertest/lib/test.js:132:12)
      - Server.g (events.js:180:16)
      - Server.EventEmitter.emit (events.js:92:17)
      - net.js:1276:10
    found:  ~
    wanted:
      name:    Error
      message: expected 200 "OK", got 301 "Moved Permanently"
      type:    ~
    type:
      found:  undefined
      wanted: undefined
  ...
# try to get /wallet page while logged in ( with session from signup )
not ok 6 should be equal
  ---
    file:   /root/safewallet/node_modules/supertest/lib/test.js
    line:   205
    column: 12
    stack:
      - getCaller (/root/safewallet/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/root/safewallet/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/root/safewallet/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/root/safewallet/node_modules/tap/lib/tap-test.js:87:16)
      - /root/safewallet/test/signups-test.js:54:9
      - Test.assert (/root/safewallet/node_modules/supertest/lib/test.js:205:12)
      - Server.assert (/root/safewallet/node_modules/supertest/lib/test.js:132:12)
      - Server.g (events.js:180:16)
      - Server.EventEmitter.emit (events.js:92:17)
      - net.js:1276:10
    found:  ~
    wanted:
      name:    Error
      message: expected 200 "OK", got 301 "Moved Permanently"
      type:    ~
    type:
      found:  undefined
      wanted: undefined
  ...
# logout of the current session
ok 7 should be equal
# try to signup another user with the same name
ok 8 should be equal
not ok 9 should be equal
  ---
    file:   /root/safewallet/test/signups-test.js
    line:   77
    column: 9
    stack:
      - getCaller (/root/safewallet/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/root/safewallet/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/root/safewallet/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/root/safewallet/node_modules/tap/lib/tap-test.js:87:16)
      - Test.<anonymous> (/root/safewallet/test/signups-test.js:77:9)
      - Test.assert (/root/safewallet/node_modules/supertest/lib/test.js:221:6)
      - Server.assert (/root/safewallet/node_modules/supertest/lib/test.js:132:12)
      - Server.g (events.js:180:16)
      - Server.EventEmitter.emit (events.js:92:17)
      - net.js:1276:10
    found:  missing
    wanted: user name is unavailable.
    diff:   |
      FOUND:  missing
      WANTED: user name is unavailable.
              ^ (at position = 0)
  ...
# try to get /account page with expired cookie
ok 10 should be equal
# try to get /wallet page with expired cookie
ok 11 should be equal
# try to log in with the first user - wrong password
ok 12 should be equal
ok 13 should be equal
# try to log in with the first user - no password
ok 14 should be equal
ok 15 should be equal
# try to log in with the first user - correct password
not ok 16 should be equal
  ---
    file:   /root/safewallet/node_modules/supertest/lib/test.js
    line:   205
    column: 12
    stack:
      - getCaller (/root/safewallet/node_modules/tap/lib/tap-assert.js:418:17)
      - assert (/root/safewallet/node_modules/tap/lib/tap-assert.js:21:16)
      - Function.equal (/root/safewallet/node_modules/tap/lib/tap-assert.js:162:10)
      - Test._testAssert [as equal] (/root/safewallet/node_modules/tap/lib/tap-test.js:87:16)
      - /root/safewallet/test/signups-test.js:135:9
      - Test.assert (/root/safewallet/node_modules/supertest/lib/test.js:205:12)
      - Server.assert (/root/safewallet/node_modules/supertest/lib/test.js:132:12)
      - Server.g (events.js:180:16)
      - Server.EventEmitter.emit (events.js:92:17)
      - net.js:1276:10
    found:  ~
    wanted:
      name:    Error
      message: expected 301 "Moved Permanently", got 200 "OK"
      type:    ~
    type:
      found:  undefined
      wanted: undefined
  ...

TypeError: Cannot call method 'destroy' of undefined
    at /root/safewallet/test/signups-test.js:142:13
    at callbackWrap (/root/safewallet/node_modules/resource/lib/method.js:152:27)
    at /root/safewallet/node_modules/resource/lib/datasource/find.js:36:7
    at /root/safewallet/node_modules/resource/node_modules/jugglingdb/lib/model.js:453:13
    at /root/safewallet/node_modules/jugglingdb-nano/lib/nano.js:280:18
    at Object.exports.handle (/root/safewallet/node_modules/jugglingdb-nano/node_modules/nano/node_modules/errs/lib/errs.js:198:5)
    at Request._callback (/root/safewallet/node_modules/jugglingdb-nano/node_modules/nano/nano.js:304:16)
    at Request.self.callback (/root/safewallet/node_modules/jugglingdb-nano/node_modules/nano/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/safewallet/node_modules/jugglingdb-nano/node_modules/nano/node_modules/request/request.js:873:14)
```

Maybe it is just _couchdb_ problem? Looks like it can't create records to database (or can't create json files). I have checked the directory where json files should be created, permissions are ok but it is empty.
I haven't found the solving of this via google.
